version: "3"

services:
  app:
    build: ./
    container_name: app
    command: ["flask", "run", "--host=0.0.0.0"]
    # command: python app.py runserver 0.0.0.0:5000
    image: app-iris:1.0
    volumes:
      - ./:/app
    ports:
      - 13000:5000
